/**
 * Intro texts for the collection pages that people actually search for (D299).
 *
 * One hundred to two hundred words per language, written for this catalogue —
 * not generated from the tag name. A slug without a text here falls back to the
 * one-line `markers.tagIntro`, which is honest but thin, so it stays out of the
 * texts we want search engines to weigh. Checked by `tag-intros.test.ts`:
 * every slug is a real catalogue tag and every text is within the word range.
 */
export type TagIntro = { en: string; ru: string };

export const TAG_INTROS: Readonly<Record<string, TagIntro>> = {
  web3: {
    en: "Web3 hiring covers far more than protocol engineering. On this page you will find roles across the whole stack — contract and infrastructure work, front-ends that talk to wallets, product and design, community, legal and compliance, research and token design. What they share is a company building on public blockchains, which changes how the work feels: releases are public, mistakes are expensive and visible, and the people you work with are spread across time zones. Pay is often quoted in dollars and sometimes partly in tokens; our cards show the figure the employer gave and the period it covers, never an estimate of ours. Each listing also states the work format and the hours a team needs you to overlap with, so you can judge the day-to-day before you apply. Some roles are posted by employers directly, others come from partner feeds and link back to the original.",
    ru: "Работа в web3 — это далеко не только протокольная разработка. На этой странице собраны роли по всему стеку: контракты и инфраструктура, фронтенд, который общается с кошельками, продукт и дизайн, комьюнити, юристы и комплаенс, исследования и токеномика. Общее у них одно — компания строит на публичных блокчейнах, и это меняет характер работы: релизы видны всем, ошибки дороги и заметны, а команда обычно размазана по часовым поясам. Зарплату часто называют в долларах, иногда частично в токенах; в карточке стоит та цифра и тот период, которые указал работодатель, своих оценок мы не добавляем. Там же видно формат работы и часы, с которыми нужно пересекаться, — характер рабочего дня понятен до отклика. Часть вакансий публикуют сами компании, часть приходит из партнёрских фидов со ссылкой на оригинал.",
  },
  defi: {
    en: "DeFi teams build the parts of finance that run as code: lending markets, exchanges, derivatives, stablecoins and the tooling around them. The hiring bar is unusual because the product holds other people's money — engineers are asked about failure modes and audits as much as about features, analysts live in on-chain data, and risk, treasury and compliance roles carry real weight. Not every opening here is technical: these companies hire designers who can make a liquidation screen readable, writers who can explain a mechanism without hype, and support people who stay calm during an incident. Listings show the work format, the employment type and the time zone the team needs, plus whatever pay range the employer published. Jobs come from companies posting with us and from partner feeds; imported ones always link back to the original posting.",
    ru: "Команды DeFi строят ту часть финансов, которая работает как код: кредитные рынки, биржи, деривативы, стейблкоины и инструменты вокруг них. Планка найма здесь своеобразная, потому что продукт держит чужие деньги: инженера спрашивают про сценарии отказа и аудиты не меньше, чем про фичи, аналитик живёт в ончейн-данных, а роли в риске, казначействе и комплаенсе имеют реальный вес. Технические вакансии — не единственные: сюда нужны дизайнеры, способные сделать экран ликвидации читаемым, авторы, умеющие объяснить механику без пафоса, и поддержка, которая не паникует во время инцидента. В карточке видны формат, тип занятости и нужный часовой пояс, а также вилка, если работодатель её назвал. Часть вакансий публикуют у нас напрямую, часть приходит из партнёрских фидов со ссылкой на оригинал.",
  },
  nft: {
    en: "NFT work has settled down since the first wave. The companies hiring now are marketplaces, infrastructure providers, game studios, ticketing and loyalty products, and brands that treat tokens as a feature rather than the whole business. That shows up in the roles: smart-contract and backend engineering, front-end work where the wallet flow is the product, art and brand design, community and partnerships, and legal roles dealing with rights and royalties. If you are coming from gaming, e-commerce or digital art, much of your experience transfers directly — the token is one layer, not a new career. Every listing states the format, the employment type and the overlap the team needs, with the pay range exactly as the employer gave it. Imported listings name their source and link to the original so you can check it yourself.",
    ru: "Работа вокруг NFT стала спокойнее, чем в первую волну. Нанимают сейчас маркетплейсы, инфраструктурные сервисы, игровые студии, продукты для билетов и лояльности и бренды, для которых токен — функция, а не весь бизнес. Это видно по ролям: смарт-контракты и бэкенд, фронтенд, где сценарий с кошельком и есть продукт, арт и бренд-дизайн, комьюнити и партнёрства, юристы по правам и роялти. Если вы из геймдева, электронной коммерции или цифрового искусства, большая часть опыта переносится напрямую: токен — это один слой, а не новая профессия. В каждой карточке указаны формат, тип занятости и нужное пересечение часов, вилка — ровно та, что назвал работодатель. У импортированных вакансий назван источник и стоит ссылка на оригинал, чтобы можно было проверить самому.",
  },
  gamefi: {
    en: "GameFi sits between two industries, and the hiring reflects it. Studios want people who can ship a game that is fun first — engine programmers, gameplay designers, artists, producers — alongside those who understand on-chain assets, marketplaces and the economy that holds a world together. Economy designers and analysts are in unusual demand here, because a game that pays out needs balancing the way a live service does. Community and support roles matter more than in a traditional studio: the players are also holders, and they notice every change. Listings here show the work format, the employment type and the hours a team needs you to share, with the pay range as published by the employer. Some are posted directly by studios, others come from partner feeds with a link to the original announcement.",
    ru: "GameFi стоит между двумя индустриями, и найм это отражает. Студиям нужны те, кто умеет выпускать игру, в которую прежде всего интересно играть, — программисты движка, геймплей-дизайнеры, художники, продюсеры, — и рядом те, кто понимает ончейн-предметы, маркетплейсы и экономику, которая держит мир. Дизайнеры экономики и аналитики востребованы здесь сильнее обычного: игра с выплатами требует балансировки, как живой сервис. Комьюнити и поддержка значат больше, чем в обычной студии: игроки здесь одновременно и держатели, они замечают каждое изменение. В карточках указаны формат работы, тип занятости и часы, с которыми нужно пересекаться, вилка — та, что опубликовал работодатель. Часть вакансий размещают сами студии, часть приходит из партнёрских фидов со ссылкой на исходное объявление.",
  },
  zk: {
    en: "Zero-knowledge work is one of the few corners of this industry where a research background pays off directly. Teams hiring here build proving systems, circuits, rollups and the compilers and tooling around them, and the openings range from cryptography research to the very practical business of making a prover faster or a client library usable. You do not need a doctorate for all of it: plenty of roles are ordinary systems engineering in Rust or C++ on a product that happens to produce proofs, and protocol teams also hire for developer relations, technical writing and product work. Each listing shows the work format, the employment type and the overlap the team expects, plus the pay range the employer published. Imported postings keep the name of their source and a link to the original.",
    ru: "Zero-knowledge — один из немногих участков отрасли, где исследовательский бэкграунд окупается напрямую. Команды здесь делают системы доказательств, схемы, роллапы и компиляторы с инструментами вокруг них, а вакансии тянутся от криптографических исследований до очень практичной работы: ускорить прувер, привести в порядок клиентскую библиотеку. Степень нужна не везде: многие роли — обычная системная разработка на Rust или C++ в продукте, который просто умеет строить доказательства, а протокольные команды берут ещё и devrel, технических писателей и продактов. В каждой карточке видны формат работы, тип занятости и ожидаемое пересечение часов, а также вилка, которую указал работодатель. У импортированных вакансий сохраняются имя источника и ссылка на оригинал.",
  },
  solidity: {
    en: "Solidity is still the language most on-chain products are written in, and the roles asking for it are not all the same job. Some teams want a contract engineer who can design a protocol and live with its upgrade path; others need someone to extend a working system carefully, write tests that catch the expensive cases, and sit through an audit. A third group is really hiring a full-stack developer who happens to touch contracts a few days a month. Reading the responsibilities matters more than the title here. Experience with EVM internals, gas, proxies and tooling such as Foundry or Hardhat is what tends to be checked. Every listing shows the format, the employment type and the time zone overlap the team needs, with the published pay range, and imported ones link back to the original.",
    ru: "Solidity по-прежнему язык, на котором написана большая часть ончейн-продуктов, и вакансии с ним — это очень разные работы. Одним командам нужен контрактный инженер, который спроектирует протокол и будет жить с его схемой обновлений; другим — человек, который аккуратно расширит работающую систему, напишет тесты на дорогие случаи и выдержит аудит. Третьи на самом деле ищут фулстек-разработчика, который заглядывает в контракты несколько дней в месяц. Здесь полезнее читать обязанности, чем заголовок. Обычно проверяют понимание внутренностей EVM, газа, прокси и инструментов вроде Foundry или Hardhat. В каждой карточке указаны формат, тип занятости и нужное пересечение часов, а также опубликованная вилка; у импортированных вакансий есть ссылка на оригинал.",
  },
  rust: {
    en: "Rust reached crypto through the places where performance and correctness both matter: validators and clients, sequencers, indexers, proving systems and the Solana and Polkadot ecosystems. The work is usually closer to systems engineering than to web development — async runtimes, memory and throughput, long-running services that cannot quietly corrupt state. That also makes it one of the easier doors into the industry from outside it, since a database, trading or embedded background transfers better than a blockchain certificate. Teams here tend to interview on reasoning about failure rather than on trivia. Each listing on this page shows the work format, the employment type and the hours a team needs you to overlap with, alongside whatever pay range the employer published; imported listings name their source and link to the original posting.",
    ru: "Rust пришёл в крипту через те места, где одновременно важны скорость и корректность: валидаторы и клиенты, секвенсеры, индексаторы, системы доказательств, экосистемы Solana и Polkadot. Работа здесь ближе к системной разработке, чем к вебу: асинхронные рантаймы, память и пропускная способность, долгоживущие сервисы, которые не имеют права тихо испортить состояние. Поэтому это один из самых удобных входов в отрасль снаружи: опыт с базами данных, трейдингом или embedded переносится лучше, чем сертификат по блокчейну. На собеседовании чаще спрашивают про рассуждение об отказах, чем про мелочи синтаксиса. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, а также вилка, если работодатель её опубликовал; у импортированных вакансий назван источник и стоит ссылка на оригинал.",
  },
  react: {
    en: "Front-end work in crypto is ordinary React work with one extra dimension: the user holds the keys. Teams hiring here build dashboards, trading screens, wallet flows and onboarding, and the hard parts are usually state that arrives late, transactions that can fail halfway, and copy that has to explain an irreversible action without frightening everyone. If you have shipped a serious React application, most of your experience applies directly — the chain-specific pieces are learnable in weeks, and many of these teams say so openly in the posting. Design systems, accessibility and performance are valued here the same as anywhere else. Each listing shows the work format, the employment type and the time-zone overlap the team expects, with the pay range exactly as the employer gave it, and imported ones link back to the original.",
    ru: "Фронтенд в крипте — это обычная работа с React плюс одно измерение: ключи находятся у пользователя. Команды делают дашборды, торговые экраны, сценарии с кошельком и онбординг, а сложное здесь — состояние, которое приходит с задержкой, транзакции, способные упасть на середине, и тексты, которые должны объяснить необратимое действие, никого не напугав. Если вы выпускали серьёзное React-приложение, большая часть опыта переносится напрямую: специфика сети осваивается за недели, и многие команды прямо пишут об этом в вакансии. Дизайн-системы, доступность и производительность ценятся здесь так же, как везде. В каждой карточке указаны формат работы, тип занятости и ожидаемое пересечение часов, вилка — ровно та, что назвал работодатель; у импортированных вакансий есть ссылка на оригинал.",
  },
  smartcontracts: {
    en: "Smart-contract roles are gathered here regardless of the language a team uses — Solidity on the EVM, Rust on Solana, Move, Cairo and the rest. What the work has in common is that the code is public, immutable once deployed and holds value, so the day looks different from ordinary backend work: more time in tests, specifications and review, and a real audit at the end. Teams usually look for people who can explain why a design is safe, not only make it work. Alongside engineering, this page collects the roles that sit next to it — security review, protocol research and the product people who decide what should be on-chain at all. Listings show the format, the employment type, the required overlap and the published pay range; imported ones keep a link to the original.",
    ru: "Вакансии по смарт-контрактам собраны здесь независимо от языка команды — Solidity на EVM, Rust на Solana, Move, Cairo и остальные. Общее в этой работе то, что код публичен, после деплоя неизменяем и держит ценность, поэтому день выглядит иначе, чем в обычном бэкенде: больше времени уходит на тесты, спецификации и ревью, а в конце ждёт настоящий аудит. Обычно ищут тех, кто может объяснить, почему решение безопасно, а не только заставить его работать. Рядом с инженерными ролями здесь собраны и соседние: ревью безопасности, протокольные исследования и продакты, которые решают, что вообще должно быть ончейн. В карточках указаны формат, тип занятости, нужное пересечение часов и опубликованная вилка; у импортированных вакансий сохраняется ссылка на оригинал.",
  },
  remote: {
    en: "Every job on this page is remote, but remote means different things to different teams. Some are fully asynchronous and will happily hire across any time zone; others say remote and expect you online for most of a European or American working day. That is why each card states the hours a team needs you to overlap with, and why the region pages group jobs by exactly that. Before applying it is worth checking three things in the listing: the overlap, whether the company can employ or contract someone in your country, and how pay is defined — gross or net, per month or per year, and in which currency. We show those fields as the employer gave them. Jobs come both from companies posting directly and from partner feeds that link back to the original.",
    ru: "Все вакансии на этой странице удалённые, но удалёнка у разных команд означает разное. Одни работают полностью асинхронно и готовы нанимать в любом часовом поясе; другие пишут «remote», а ждут вас онлайн почти весь европейский или американский рабочий день. Поэтому в каждой карточке указаны часы, с которыми нужно пересекаться, и поэтому страницы регионов группируют вакансии именно по этому признаку. Перед откликом стоит проверить в объявлении три вещи: пересечение часов, может ли компания оформить человека в вашей стране и как описана оплата — гросс или нет, в месяц или в год и в какой валюте. Эти поля мы показываем ровно так, как их дал работодатель. Часть вакансий публикуют компании напрямую, часть приходит из партнёрских фидов со ссылкой на оригинал.",
  },
  senior: {
    en: "Senior titles are not comparable between companies, and in crypto the spread is wider than usual: the same word covers a third engineer at a six-person protocol team and a specialist inside a large exchange. The postings collected here do have something in common — they expect you to choose between approaches and defend the choice, to work without someone breaking the task down for you, and often to be the person others ask. Scope is the thing worth reading closely: whether you own a system, a team or a roadmap changes the job more than the title does. Each listing shows the work format, the employment type and the overlap the team needs, with the pay range as the employer published it. Imported listings name their source and link to the original posting.",
    ru: "Слово «senior» в разных компаниях значит разное, а в крипте разброс шире обычного: за ним может стоять и третий инженер в протокольной команде из шести человек, и узкий специалист внутри крупной биржи. Но у собранных здесь вакансий есть общее: от вас ждут выбора между подходами и умения его защитить, работы без того, чтобы задачу разложили за вас, и часто роли человека, к которому приходят с вопросами. Внимательнее всего стоит читать зону ответственности: владеете вы системой, командой или дорожной картой — это меняет работу сильнее, чем название должности. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — та, что опубликовал работодатель. У импортированных вакансий назван источник и стоит ссылка на оригинал.",
  },
  entry: {
    en: "Junior and entry-level openings are the scarcest part of this market, so it is worth being deliberate about them. The teams that do hire at this level usually say what they will teach and what they expect on day one, and they tend to value visible work — a repository, a contribution to a protocol, a written explanation of something you figured out — over a list of courses. Non-engineering roles are often the easier entry point: community, support, content and operations hire juniors more readily than protocol teams do, and they lead somewhere. Check the overlap and the employment type before applying, since a first contract abroad is where surprises live. Each listing shows those fields and the pay range exactly as the employer published them, with imported postings linking back to the original.",
    ru: "Джуниорские и стартовые вакансии — самая дефицитная часть этого рынка, поэтому к ним стоит подходить осознанно. Команды, которые всё же берут на этом уровне, обычно прямо пишут, чему научат и что ждут с первого дня, и ценят видимую работу — репозиторий, вклад в протокол, внятный разбор того, в чём вы разобрались, — больше, чем список курсов. Нетехнические роли часто оказываются более простым входом: комьюнити, поддержка, контент и операции берут новичков охотнее протокольных команд, и из них есть куда расти. Перед откликом проверьте пересечение часов и тип занятости: именно в первом зарубежном контракте и живут сюрпризы. В карточке эти поля и вилка показаны ровно так, как их дал работодатель, а у импортированных вакансий есть ссылка на оригинал.",
  },
  europe: {
    en: "This page gathers jobs you can do from European working hours. It is not about where a company is registered: we compare the hours a team asks you to be available with a European day and keep the roles that overlap by at least four hours. That is usually what decides whether remote work is comfortable — a team in Berlin or Lisbon and a team in San Francisco can both call a job remote and mean very different evenings for you. Many of the companies here are distributed rather than European, which is why the list changes as new postings arrive. Each card still shows the exact time zone requirement, the work format, the employment type and the published pay range, so you can check the detail yourself before applying.",
    ru: "Здесь собраны вакансии, которые можно делать из европейского рабочего дня. Речь не о том, где зарегистрирована компания: мы сравниваем часы, в которые команда просит быть на связи, с европейским днём и оставляем те роли, где пересечение не меньше четырёх часов. Обычно именно это и решает, комфортна ли удалённая работа: команда из Берлина и команда из Сан-Франциско могут одинаково называть вакансию удалённой, но вечера у вас будут совершенно разные. Многие компании в этом списке не европейские, а распределённые, поэтому подборка меняется по мере появления новых объявлений. В каждой карточке всё равно указаны точное требование по часовому поясу, формат работы, тип занятости и опубликованная вилка — детали можно проверить до отклика.",
  },
  "north-america": {
    en: "These are the roles that line up with a North American working day. We do not filter by company address; we compare the hours a team needs you available with a day on the east coast and keep what overlaps by at least four hours. In practice that covers most companies headquartered in the United States and Canada, plus distributed teams that keep their meetings in American afternoons — which is worth knowing if you are applying from Europe, where that turns into evening work. Employment is the other thing to check here: many of these companies can only hire through a contractor agreement outside their own country. Every card shows the time zone requirement, the work format, the employment type and the pay range as the employer published it.",
    ru: "Здесь собраны роли, которые ложатся на североамериканский рабочий день. Мы не фильтруем по адресу компании: мы сравниваем часы, в которые команда просит быть на связи, с днём восточного побережья и оставляем то, где пересечение не меньше четырёх часов. На практике сюда попадает большинство компаний из США и Канады, а также распределённые команды, держащие встречи во второй половине американского дня, — это стоит учитывать, если вы откликаетесь из Европы, где это превращается в вечернюю работу. Второе, что здесь важно проверить, — оформление: многие такие компании вне своей страны могут работать только по договору подряда. В каждой карточке указаны требование по часовому поясу, формат работы, тип занятости и вилка в том виде, в каком её опубликовал работодатель.",
  },
  latam: {
    en: "Jobs on this page overlap with a Latin American working day by at least four hours. The region has become a common answer for companies that want to work in American hours without hiring in the United States, so you will find both local employers and distributed teams that simply need someone awake in these time zones. Contract work is more usual here than full employment, and pay is frequently quoted in dollars — both facts are stated in the listing rather than implied, including the period and whether the figure is gross. If a company can only engage contractors in your country, that is normally written in the posting too. Every card also shows the exact overlap required and the work format, and imported listings keep a link to the original announcement.",
    ru: "Вакансии на этой странице пересекаются с латиноамериканским рабочим днём не меньше чем на четыре часа. Регион стал частым ответом для компаний, которым нужен американский график без найма в США, поэтому здесь встречаются и местные работодатели, и распределённые команды, которым просто нужен человек, бодрствующий в этих поясах. Договор подряда здесь встречается чаще полноценного трудоустройства, а зарплату часто называют в долларах — и то и другое указано в объявлении прямо, вместе с периодом и пометкой, гросс ли это. Если компания может оформить в вашей стране только подрядчика, об этом обычно тоже написано в вакансии. В каждой карточке видны точное требование по пересечению часов и формат работы, а у импортированных вакансий сохраняется ссылка на исходное объявление.",
  },
  apac: {
    en: "This collection keeps the roles that work from Asian and Pacific hours — at least four hours of overlap with a Singapore working day. It is the hardest region to fill from a European or American job board, because a team that runs its day in London simply cannot be done well from Tokyo, so filtering by overlap saves more time here than anywhere else. The companies that do appear tend to be exchanges, infrastructure teams and studios with a genuine presence in the region, plus asynchronous teams that do not care when you work at all. Check the employment type carefully: hiring rules differ sharply between countries here. Each card shows the overlap requirement, the work format, the employment type and the pay range exactly as the employer gave it.",
    ru: "В этой подборке остаются роли, которые реально делать из азиатских и тихоокеанских часов: пересечение с рабочим днём Сингапура не меньше четырёх часов. Это самый сложный регион для обычной доски вакансий: команду, живущую по лондонскому дню, из Токио нормально не вытянуть, поэтому фильтр по пересечению экономит здесь больше времени, чем где-либо ещё. Чаще всего сюда попадают биржи, инфраструктурные команды и студии с реальным присутствием в регионе, а также асинхронные команды, которым вообще всё равно, когда вы работаете. Внимательно смотрите на тип занятости: правила оформления в странах региона сильно расходятся. В каждой карточке указаны требование по пересечению часов, формат работы, тип занятости и вилка ровно в том виде, в каком её дал работодатель.",
  },
  "africa-mena": {
    en: "Here are the roles that fit an African or Middle Eastern working day, measured as at least four hours of overlap with Lagos. The region sits conveniently between European and Asian hours, which is why distributed teams often end up hiring here even when they never set out to, and why many of the listings on this page are from companies with no local office at all. Payments and employment are the parts worth reading closely: contractor agreements and dollar or stablecoin payouts are common, and the listing says which applies rather than leaving you to guess. Each card shows the overlap a team needs, the work format, the employment type and the published pay range, and imported postings name their source and link back to the original.",
    ru: "Здесь собраны роли, которые ложатся на африканский и ближневосточный рабочий день — пересечение с Лагосом не меньше четырёх часов. Регион удобно расположен между европейскими и азиатскими часами, поэтому распределённые команды часто нанимают здесь, даже если изначально не планировали, и поэтому многие вакансии на этой странице — от компаний без местного офиса вообще. Внимательнее всего стоит читать про оплату и оформление: договор подряда и выплаты в долларах или стейблкоинах здесь обычное дело, и в объявлении написано, что именно предлагается, а не оставлено на догадки. В каждой карточке указаны нужное пересечение часов, формат работы, тип занятости и опубликованная вилка, а у импортированных вакансий назван источник и стоит ссылка на оригинал.",
  },
  "eco-ethereum": {
    en: "Ethereum is where most on-chain hiring still happens, and the ecosystem is wide enough that two jobs here can have nothing in common. Core protocol and client work sits at one end, with research, consensus and execution clients; at the other are rollups, wallets, infrastructure providers, indexers and the thousands of applications that treat the chain as a settlement layer. Tooling is mature by the standards of this industry, which means teams expect you to know the ecosystem's conventions — Foundry or Hardhat, the standard token interfaces, how an upgrade is coordinated. It is also the easiest place to learn in public: the specifications, the clients and most of the applications are open. Each listing on this page shows the work format, the employment type and the overlap a team needs, with the pay range exactly as the employer published it.",
    ru: "Ethereum — место, где по-прежнему происходит большая часть ончейн-найма, и экосистема здесь настолько широкая, что две вакансии могут не иметь между собой ничего общего. На одном краю — работа над протоколом и клиентами, исследования, консенсус и исполнение; на другом — роллапы, кошельки, инфраструктурные сервисы, индексаторы и тысячи приложений, для которых сеть просто слой расчётов. Инструменты здесь зрелые по меркам отрасли, и от вас ждут знания принятых в экосистеме соглашений: Foundry или Hardhat, стандартные интерфейсы токенов, порядок согласования обновлений. Это же и самое удобное место, чтобы учиться в открытую: спецификации, клиенты и большинство приложений открыты. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — та, что опубликовал работодатель.",
  },
  "eco-solana": {
    en: "Solana teams hire differently from the rest of the industry because the chain itself pushes them towards performance. Programs are written in Rust, usually with Anchor, and the people who do well here tend to come from systems engineering rather than from web development. Around the programs sit validators, RPC providers, indexers, consumer wallets and payment products, plus a notably large share of mobile and consumer-facing work — this is one of the few ecosystems where a designer or a mobile engineer is as likely to be hired as a protocol specialist. Expect questions about throughput, accounts and compute limits rather than about gas. Each listing here states the work format, the employment type and the hours a team needs you to share, alongside the published pay range; imported ones link back to the original posting.",
    ru: "Команды на Solana нанимают иначе, чем остальная отрасль, потому что сама сеть толкает их к производительности. Программы пишут на Rust, обычно с Anchor, и лучше здесь себя чувствуют те, кто пришёл из системной разработки, а не из веба. Вокруг программ — валидаторы, RPC-провайдеры, индексаторы, пользовательские кошельки и платёжные продукты, а также заметно большая доля мобильной и потребительской работы: это одна из немногих экосистем, где дизайнера или мобильного разработчика берут не реже протокольного специалиста. Спрашивать будут про пропускную способность, модель аккаунтов и лимиты вычислений, а не про газ. В каждой карточке указаны формат работы, тип занятости и часы, с которыми нужно пересекаться, рядом — опубликованная вилка; у импортированных вакансий есть ссылка на оригинал.",
  },
  exchange: {
    en: "Exchanges and trading venues are the most conventional employers in crypto, and that shows in the hiring. These are companies with real operations: matching engines and risk systems, custody, market data, settlement, support desks that work in shifts, and compliance teams that grow every year. Engineering roles lean towards low latency and correctness, often in Go, Java, C++ or Rust, while the non-engineering side — compliance, finance, support, fraud and partnerships — makes up a larger share of the openings than anywhere else on this site. Licensing shapes the work: a venue regulated in one jurisdiction cannot always hire or serve in another, which is why the listings state employment type and location limits explicitly. Each card also shows the work format, the required overlap and the pay range as published.",
    ru: "Биржи и торговые площадки — самые обычные работодатели в крипте, и это видно по найму. Это компании с настоящими операциями: матчинг и системы риска, хранение активов, рыночные данные, расчёты, поддержка посменно и комплаенс, который растёт каждый год. Инженерные роли тяготеют к низким задержкам и корректности, часто на Go, Java, C++ или Rust, а нетехническая часть — комплаенс, финансы, поддержка, антифрод, партнёрства — занимает здесь большую долю вакансий, чем где-либо ещё на сайте. Работу определяет лицензирование: площадка, регулируемая в одной юрисдикции, не всегда может нанимать или обслуживать в другой, поэтому в объявлениях прямо указаны тип занятости и ограничения по странам. В карточке также видны формат работы, нужное пересечение часов и опубликованная вилка.",
  },
  dao: {
    en: "Working for a DAO is less exotic than it sounds and more unusual than a job description can convey. The work itself — engineering, design, operations, governance, treasury, community — looks familiar; what differs is who decides. Budgets and sometimes roles are approved by token holders, contributions are visible, and a contract may run for a season rather than indefinitely. That suits people who are comfortable writing proposals and working without a manager, and frustrates people who want a clear chain of command. Pay is frequently in stablecoins and quoted per month, and engagement is almost always a contract rather than employment — both are stated in the listing rather than implied. Each card shows the work format, the employment type and the overlap a team expects; imported listings keep a link to their original source.",
    ru: "Работа в DAO звучит экзотичнее, чем есть, но устроена непривычнее, чем передаёт описание вакансии. Сама работа — разработка, дизайн, операции, управление, казначейство, комьюнити — выглядит знакомо; отличается то, кто принимает решения. Бюджеты, а иногда и сами роли утверждают держатели токенов, вклад каждого виден, а контракт может быть на сезон, а не бессрочным. Это подходит тем, кому комфортно писать предложения и работать без руководителя, и раздражает тех, кому нужна понятная вертикаль. Платят часто в стейблкоинах и в расчёте на месяц, оформление почти всегда подрядное, а не трудовое, — и то и другое указано в объявлении прямо. В карточке видны формат работы, тип занятости и ожидаемое пересечение часов, у импортированных вакансий сохраняется ссылка на источник.",
  },
  engineering: {
    en: "This is the largest collection on the site: everything from protocol and contract work to backend services, infrastructure, data platforms, mobile and front-end. If you are arriving from outside crypto, the useful thing to know is that most of these jobs are ordinary engineering with one unusual constraint — some part of the system is public and cannot be quietly fixed later. That raises the value of testing, review and clear reasoning, and lowers the value of moving fast for its own sake. Experience from fintech, gaming, trading or infrastructure transfers well; the chain-specific knowledge is usually learned on the job, and many postings say so. Use the level, skill and region collections to narrow this list down. Every card shows the work format, the employment type, the required overlap and the published pay range.",
    ru: "Это самая большая подборка на сайте: от протокольной и контрактной работы до бэкенд-сервисов, инфраструктуры, платформ данных, мобильной разработки и фронтенда. Если вы приходите снаружи крипты, полезно знать главное: большая часть этих вакансий — обычная инженерия с одним непривычным ограничением, когда часть системы публична и её нельзя тихо починить потом. Это повышает ценность тестов, ревью и внятных рассуждений и снижает ценность скорости ради скорости. Опыт из финтеха, геймдева, трейдинга или инфраструктуры переносится хорошо, а специфику сети обычно осваивают в работе — многие объявления так и пишут. Сузить список помогут подборки по уровню, навыку и региону. В каждой карточке указаны формат работы, тип занятости, нужное пересечение часов и опубликованная вилка.",
  },
  design: {
    en: "Design in crypto has a harder job than in most products: the interface has to explain irreversible actions, unfamiliar words and real financial risk to people who are often in a hurry. The teams hiring here want product designers who can simplify a flow without hiding what matters, and they increasingly care about research and writing as part of the role. Brand and motion work appears too, usually at consumer products and games, and design systems work shows up wherever a team has outgrown its first interface. A portfolio that shows decisions and trade-offs carries more weight than a reel of screens. Each listing on this page shows the work format, the employment type and the time-zone overlap a team needs, with the pay range exactly as the employer gave it; imported listings link back to the original.",
    ru: "У дизайна в крипте задача сложнее, чем в большинстве продуктов: интерфейс должен объяснить необратимые действия, незнакомые слова и настоящий финансовый риск людям, которые часто спешат. Команды ищут продуктовых дизайнеров, умеющих упростить сценарий, не спрятав важное, и всё чаще считают частью роли исследования и тексты. Встречается и бренд с анимацией — обычно в потребительских продуктах и играх, — а работа над дизайн-системой появляется там, где команда переросла свой первый интерфейс. Портфолио, в котором видны решения и компромиссы, весит больше, чем набор красивых экранов. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — ровно та, что дал работодатель; у импортированных вакансий есть ссылка на оригинал.",
  },
  marketing: {
    en: "Marketing roles here range from growth and performance work to content, brand, partnerships and the particular craft of launching something people are right to be sceptical about. The useful distinction when reading these postings is between teams marketing a product with real users and teams marketing a token — the day-to-day, the metrics and the professional risk are different, and the listing usually makes it clear which one you are looking at. Channels skew towards communities, newsletters and events rather than paid acquisition, since much of the audience sits in places advertising cannot reach. Regulatory limits on what may be promised are real and worth asking about in the interview. Each card shows the work format, the employment type, the overlap required and the pay range published by the employer.",
    ru: "Маркетинговые вакансии здесь тянутся от growth и performance до контента, бренда, партнёрств и особого ремесла — запускать то, к чему люди справедливо относятся скептически. Читая объявления, полезно различать команды, которые продвигают продукт с реальными пользователями, и команды, которые продвигают токен: будни, метрики и профессиональный риск у них разные, и из вакансии обычно понятно, что перед вами. Каналы смещены в сторону сообществ, рассылок и мероприятий, а не платного трафика, потому что значительная часть аудитории сидит там, куда реклама не достаёт. Ограничения на то, что вообще можно обещать, здесь реальны, и про них стоит спросить на собеседовании. В карточке указаны формат работы, тип занятости, нужное пересечение часов и опубликованная работодателем вилка.",
  },
  community: {
    en: "Community and developer relations are closer to the centre of a crypto company than they are almost anywhere else: the users are often holders, the support channel is public, and a badly handled incident becomes a story within minutes. The roles split roughly in two. Community managers and moderators keep a space usable, answer the same questions patiently and feed what they hear back to the product. Developer relations sits nearer engineering — writing documentation and examples, helping teams integrate, and being honest with your own engineers about what is confusing. Both are shift-shaped work in a global audience, so the time-zone requirement in the listing matters more than usual. Each card shows the work format, the employment type, the required overlap and the pay range as the employer published it.",
    ru: "Комьюнити и devrel в криптокомпании ближе к центру, чем почти где-либо ещё: пользователи часто ещё и держатели, канал поддержки публичен, а плохо отработанный инцидент становится историей за минуты. Роли делятся примерно надвое. Комьюнити-менеджеры и модераторы держат пространство пригодным для жизни, терпеливо отвечают на одни и те же вопросы и возвращают услышанное в продукт. Devrel стоит ближе к разработке: документация и примеры, помощь командам с интеграцией и честный разговор со своими же инженерами о том, что непонятно. И то и другое — работа со сменным характером на глобальную аудиторию, поэтому требование по часовому поясу здесь важнее обычного. В карточке указаны формат работы, тип занятости, нужное пересечение часов и вилка в том виде, в каком её опубликовал работодатель.",
  },
  "infra-l1l2": {
    en: "Layer one and layer two teams build the rails everything else runs on: consensus and execution clients, sequencers, bridges, data availability, node and RPC infrastructure. The work is unusually close to classic distributed systems — if you have run databases, message queues or large fleets of servers, the problems here will look familiar even if the vocabulary does not. Reliability matters more than speed of delivery, because an outage in this layer stops every application above it, and the on-call rotation is real. Roles range from protocol engineering and research to the far more ordinary work of keeping nodes healthy and documentation current. Each listing shows the work format, the employment type and the overlap a team needs, with the pay range exactly as the employer published it; imported ones link back to the original.",
    ru: "Команды первого и второго уровня строят рельсы, по которым едет всё остальное: клиенты консенсуса и исполнения, секвенсеры, мосты, доступность данных, инфраструктура нод и RPC. Работа здесь необычно близка к классическим распределённым системам: если вы держали базы данных, очереди сообщений или большие парки серверов, задачи покажутся знакомыми, даже если словарь незнаком. Надёжность важнее скорости поставки, потому что авария на этом уровне останавливает все приложения выше, и дежурства здесь настоящие. Роли тянутся от протокольной инженерии и исследований до куда более обыденной работы: держать ноды здоровыми, а документацию — свежей. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — та, что опубликовал работодатель; у импортированных вакансий есть ссылка на оригинал.",
  },
  metaverse: {
    en: "Metaverse hiring survived the hype cycle in a quieter form. The teams posting today build virtual worlds, avatar and identity systems, creator tools, and the commerce and infrastructure underneath them, often with a games engine at the centre. That makes the skill set recognisable: Unity or Unreal, 3D art and technical art, networking and backend for persistent worlds, plus product and community roles. The on-chain part is usually ownership — items, land, identity — rather than the whole product, so blockchain experience helps but rarely decides. If you come from games or from AR and VR, read the listing for how much of the job is world-building and how much is token mechanics. Each card shows the work format, the employment type, the required overlap and the published pay range.",
    ru: "Найм вокруг метавселенных пережил волну хайпа в более спокойной форме. Команды, которые публикуют вакансии сегодня, строят виртуальные миры, системы аватаров и идентичности, инструменты для авторов, а также коммерцию и инфраструктуру под ними — чаще всего с игровым движком в центре. Поэтому набор навыков узнаваем: Unity или Unreal, 3D и техническое арт-направление, сеть и бэкенд для постоянных миров, плюс продуктовые и комьюнити-роли. Ончейн-часть обычно отвечает за владение — предметы, земля, идентичность, — а не за весь продукт, так что опыт с блокчейном помогает, но редко решает. Если вы из геймдева или из AR и VR, смотрите в объявлении, сколько в работе построения мира и сколько токеномики. В карточке указаны формат, тип занятости, нужное пересечение часов и опубликованная вилка.",
  },
  memecoins: {
    en: "Meme projects hire, and pretending otherwise would not help anyone looking for work. What they need is usually marketing, community, design and front-end engineering, delivered faster than anywhere else in this industry — a launch window is days, not quarters. Be clear-eyed about the trade: pay is sometimes partly in the project's own token, contracts are short, and a project can disappear between your first interview and your first month. It is worth asking who funds the payroll, what happens if the token falls, and whether the contract is signed with a company or an anonymous team. We show pay exactly as the employer stated it and mark these listings as we do any other. Each card gives the work format, the employment type and the overlap a team expects.",
    ru: "Мем-проекты нанимают, и делать вид, что это не так, не поможет тому, кто ищет работу. Нужны им обычно маркетинг, комьюнити, дизайн и фронтенд, причём быстрее, чем где-либо ещё в отрасли: окно запуска — дни, а не кварталы. Стоит трезво смотреть на обмен: платят иногда частично собственным токеном проекта, контракты короткие, а сам проект может исчезнуть между первым собеседованием и первым месяцем работы. Полезно спросить, из чего платят зарплату, что будет, если токен упадёт, и с кем подписывается договор — с компанией или с анонимной командой. Оплату мы показываем ровно так, как её назвал работодатель, и размечаем такие вакансии как любые другие. В карточке есть формат работы, тип занятости и ожидаемое пересечение часов.",
  },
  "crypto-vc": {
    en: "Funds and investment firms are a small but steady part of this market, and they hire differently from the companies they back. Analyst and associate roles involve sourcing, diligence and a great deal of writing; platform roles support portfolio companies with recruiting, marketing or engineering advice; and a growing number of funds employ researchers and engineers outright, to read code before a cheque is written. Finance, legal and operations roles sit alongside them. A background in traditional venture, banking or research transfers well, and so does having actually shipped something — funds increasingly want people who have been on the other side. Each listing on this page shows the work format, the employment type and the time-zone overlap the team needs, plus the pay range exactly as it was published.",
    ru: "Фонды и инвесткомпании — небольшая, но устойчивая часть этого рынка, и нанимают они иначе, чем компании, в которые вкладываются. Роли аналитика и associate — это поиск сделок, due diligence и очень много письменной работы; platform-роли помогают портфельным компаниям с наймом, маркетингом или инженерными советами; всё больше фондов держат в штате исследователей и инженеров, чтобы читать код до того, как выписан чек. Рядом — финансы, юристы и операции. Опыт из классического венчура, банков или ресёрча переносится хорошо, и не хуже переносится опыт человека, который сам что-то выпускал: фонды всё чаще хотят тех, кто побывал по другую сторону. В карточке указаны формат работы, тип занятости и нужное пересечение часов, а также вилка в опубликованном виде.",
  },
  "ai-ml": {
    en: "Machine learning roles on this site come from two directions. Some are at AI companies that pay in the same places crypto teams recruit — remote, globally, often in dollars — and have nothing to do with blockchains. Others are inside crypto products: fraud and risk scoring, market prediction, search and matching, agents that act on-chain, and the ordinary data plumbing all of that needs. The split matters when you read a posting, because the first kind usually wants depth in modelling and the second wants someone comfortable shipping a model into a product that handles money. Data engineering and analytics roles appear here too. Each card shows the work format, the employment type and the overlap a team needs, with the pay range exactly as the employer gave it.",
    ru: "Вакансии по машинному обучению приходят сюда с двух сторон. Часть — из AI-компаний, которые нанимают там же, где и криптокоманды: удалённо, по всему миру, часто в долларах, — и к блокчейнам отношения не имеют. Часть — внутри криптопродуктов: антифрод и скоринг рисков, прогнозы рынка, поиск и подбор, агенты, действующие ончейн, и вся обычная дата-обвязка, которая для этого нужна. Это различие важно при чтении объявления: первым обычно нужна глубина в моделировании, вторым — человек, которому комфортно довести модель до продукта, работающего с деньгами. Роли дата-инженеров и аналитиков встречаются здесь же. В карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — ровно та, что дал работодатель.",
  },
  gamedev: {
    en: "Game development roles here come from studios of every size, from a handful of people shipping a mobile title to teams with a live service and a decade of history. Engine and gameplay programming, art and technical art, design, production, QA and live operations all appear. Some of these studios use on-chain ownership for items or currencies and some do not mention it at all — the listing says which, and it is worth reading, because it changes who you report to and how the economy is run. Remote work is normal in this industry but time zones are not: a live service needs overlapping hours, which is why each card states the overlap a team needs alongside the work format, the employment type and the published pay range.",
    ru: "Вакансии в геймдеве приходят сюда из студий любого размера: от нескольких человек, выпускающих мобильную игру, до команд с живым сервисом и десятилетней историей. Встречаются программирование движка и геймплея, арт и технический арт, дизайн, продюсирование, QA и live-операции. Часть студий использует ончейн-владение для предметов или валют, часть не упоминает об этом вовсе — в объявлении написано, что именно, и это стоит прочитать: от этого зависит, кому вы подчиняетесь и как управляется экономика. Удалённая работа в индустрии норма, а вот часовые пояса — нет: живому сервису нужны пересекающиеся часы, поэтому в каждой карточке указано нужное пересечение, а рядом — формат работы, тип занятости и опубликованная вилка.",
  },
  product: {
    en: "Product roles in crypto carry an unusual amount of judgement. You are deciding not only what to build but how much of it should be on-chain, how much custody a user should have, and what you are allowed to promise under the rules that apply to the company. Teams are small, so the job is often discovery, specification, launch and support at once, with analytics you set up yourself. The best preparation is having used the products: these interviews tend to go into how a particular flow works and why it is annoying. Roles range from associate product manager at an exchange to protocol-adjacent product work where your counterpart is a researcher. Each card shows the work format, the employment type, the overlap required and the pay range as published by the employer.",
    ru: "Продуктовые роли в крипте требуют необычно много здравого смысла. Вы решаете не только что строить, но и сколько из этого должно быть ончейн, сколько контроля над активами остаётся у пользователя и что вообще можно обещать по правилам, под которые попадает компания. Команды небольшие, поэтому работа часто совмещает исследование, постановку, запуск и поддержку, а аналитику вы настраиваете себе сами. Лучшая подготовка — пользоваться этими продуктами: на собеседованиях охотно разбирают конкретный сценарий и то, чем он неудобен. Роли тянутся от associate product manager на бирже до продуктовой работы рядом с протоколом, где ваш собеседник — исследователь. В карточке указаны формат работы, тип занятости, нужное пересечение часов и опубликованная работодателем вилка.",
  },
  data: {
    en: "Data work in this industry has one property you will not find elsewhere: a large part of the raw material is public. Chain data is open, which means analysts and engineers here spend their time on indexing, decoding and modelling it rather than on begging other departments for access. The roles cover analytics engineering, pipelines and warehouses, business and product analysis, risk and fraud work at exchanges, and research that ends in a published dashboard rather than an internal slide. SQL is table stakes; the differentiator is usually being able to explain what a number means and what it does not. Each listing shows the work format, the employment type and the time-zone overlap the team needs, with the pay range exactly as the employer published it.",
    ru: "У работы с данными в этой отрасли есть свойство, которого нет больше нигде: значительная часть сырья публична. Ончейн-данные открыты, поэтому аналитики и инженеры здесь тратят время на индексацию, декодирование и моделирование, а не на выпрашивание доступов у соседних отделов. Роли закрывают аналитическую инженерию, пайплайны и хранилища, продуктовую и бизнес-аналитику, риски и антифрод на биржах, а также исследования, которые заканчиваются публичным дашбордом, а не внутренним слайдом. SQL — это входной билет; отличает обычно умение объяснить, что цифра значит и чего она не значит. В каждой карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — та, что опубликовал работодатель.",
  },
  legal: {
    en: "Legal and compliance hiring has grown faster than almost anything else here, because the rules caught up with the industry. The roles split between regulatory and compliance work — licensing, AML and KYC programmes, sanctions screening, reporting — and commercial legal work: contracts, corporate structure, intellectual property, token issuance. Experience from banking, payments or fintech transfers directly, and in many postings it is preferred over crypto-native experience. Jurisdiction matters more than in any other collection on this site: a role may require a qualification in a particular country or the right to work there, and the listing normally says so. Each card shows the work format, the employment type and the overlap a team needs, alongside the published pay range; imported listings link back to the original.",
    ru: "Найм юристов и комплаенса вырос здесь быстрее почти всего остального — правила догнали отрасль. Роли делятся на регуляторную и комплаенс-часть (лицензии, программы AML и KYC, проверка санкционных списков, отчётность) и коммерческую юридическую работу: договоры, корпоративная структура, интеллектуальная собственность, выпуск токенов. Опыт из банков, платежей или финтеха переносится напрямую, и во многих объявлениях он предпочтительнее крипто-нативного. Юрисдикция здесь важнее, чем в любой другой подборке на сайте: роль может требовать квалификации конкретной страны или права там работать, и обычно в вакансии это написано. В карточке указаны формат работы, тип занятости и нужное пересечение часов, рядом — опубликованная вилка; у импортированных вакансий есть ссылка на оригинал.",
  },
  content: {
    en: "Writing jobs in crypto are mostly about making difficult things clear to people who did not ask for a lecture. The work splits into technical writing and documentation, where you sit close to engineers and your output is read by other developers; editorial and marketing content, where the challenge is saying something true about a product that is easy to overclaim; research writing, which turns on-chain data into an argument; and localisation, because most of these products ship in several languages. Teams usually ask for samples rather than degrees, and they notice whether you can explain a mechanism without borrowing the slogans. Each listing shows the work format, the employment type and the required overlap, with the pay range as the employer published it.",
    ru: "Работа с текстами в крипте в основном про то, чтобы сделать сложное понятным людям, которые не просили лекцию. Она делится на техническое письмо и документацию, где вы сидите рядом с инженерами и вашу работу читают другие разработчики; редакционный и маркетинговый контент, где сложность — сказать о продукте правду, которую легко превратить в преувеличение; исследовательские тексты, превращающие ончейн-данные в аргумент; и локализацию, потому что большинство этих продуктов выходят на нескольких языках. Обычно просят примеры работ, а не дипломы, и замечают, умеете ли вы объяснить механику, не заимствуя лозунги. В карточке указаны формат работы, тип занятости и нужное пересечение часов, вилка — в опубликованном виде.",
  },
  "non-technical": {
    en: "Not every job in this industry needs code, and this collection exists because the assumption that it does keeps good people out. Here you will find community and support, marketing and content, sales and partnerships, operations, finance, legal and compliance, recruiting and people roles, product and research. Most of these skills transfer from any other industry — what you have to add is enough literacy to know what your company actually does, which takes weeks of reading, not a career change. Support and community are the most common first step, and they lead somewhere. Check the overlap and the employment type before applying, especially for a first contract abroad. Each card shows those fields and the pay range exactly as the employer gave them.",
    ru: "Далеко не для каждой работы в этой отрасли нужен код, и эта подборка существует потому, что обратное убеждение держит хороших людей снаружи. Здесь собраны комьюнити и поддержка, маркетинг и контент, продажи и партнёрства, операции, финансы, юристы и комплаенс, рекрутинг и HR, продукт и исследования. Большая часть этих навыков переносится из любой другой индустрии — добавить нужно грамотность, достаточную, чтобы понимать, чем на самом деле занимается ваша компания, а это недели чтения, а не смена профессии. Поддержка и комьюнити чаще всего становятся первым шагом, и из них есть куда расти. Перед откликом проверьте пересечение часов и тип занятости, особенно для первого зарубежного контракта. В карточке эти поля и вилка показаны ровно так, как их дал работодатель.",
  },
  "high-paying": {
    en: "This page keeps the listings whose published pay clears our high-pay threshold, converted to dollars at the current reference rate. Two warnings are worth more than the list itself. First, a high number is not an offer: ranges are wide, the top of a band usually belongs to someone already senior in that company, and tokens quoted at today's price are not salary. Second, a job with no range is not necessarily worse paid — many employers simply do not publish one, and those roles cannot appear here at all. Read the gross or net marking and the period, since a monthly net figure and an annual gross figure are not comparable. Each card shows the work format, the employment type and the overlap the team needs.",
    ru: "На этой странице остаются вакансии, у которых опубликованная оплата превышает наш порог высокой зарплаты, пересчитанный в доллары по текущему справочному курсу. Два предупреждения здесь полезнее самого списка. Первое: большая цифра — это не оффер. Вилки широкие, верх диапазона обычно достаётся тому, кто уже силён внутри этой компании, а токены, посчитанные по сегодняшней цене, зарплатой не являются. Второе: вакансия без вилки не обязательно хуже оплачивается — многие работодатели просто не публикуют её, и такие роли сюда не попадают вовсе. Смотрите на пометку гросс или нет и на период: месячная сумма на руки и годовая до вычетов несравнимы. В карточке указаны формат работы, тип занятости и нужное пересечение часов.",
  },
};

/** The intro written for this collection, or null when it has none yet. */
export function tagIntro(slug: string, locale: string): string | null {
  const intro = TAG_INTROS[slug];
  if (!intro) return null;
  return locale === "ru" ? intro.ru : intro.en;
}
